### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Mor223** [Inv0k3r/dota2_csgo_watcher_bot#12]
配置好config之后，在powershell里运行run.py后提示
Traceback (most recent call last):
  File "run.py", line 94, in <module>
    main()
  File "run.py", line 90, in main
    update(player_num=player_num)
  File "run.py", line 81, in update
    time.sleep((24 * 60 * 60) / (100000 / (2 * player_num)))
KeyboardInterrupt

**Comment by Inv0k3r** [comment]
emmm这个不是你自己ctrl+c停了的话可能是脚本有问题，等我再测试一下吧

**Comment by Mor223** [comment]
啊没想到回复的这么快，谢谢谢谢！
是从max上看到的大佬帖子
大佬加油！
